# Shared build/run engine for every problem in this repo.
#
# Included by three tiers of Makefile, each setting different context:
#   - the root Makefile            (no SECTION, no IS_LEAF)
#   - a section Makefile           (SECTION := Codeforces, CSES, ...)
#   - a per-problem leaf Makefile  (IS_LEAF := 1, auto-generated by `make new`)
#
# How the target problem directory (ABS) is resolved, in order:
#   1. IS_LEAF is set          -> the current directory
#   2. P=<path> is given       -> SECTION/<path>, or just <path> at the root
#   3. inside a section, no P  -> the most recently touched problem in that section
#   4. at the root, no P       -> the most recently touched problem anywhere

ROOT := $(shell git rev-parse --show-toplevel)

CXX      := g++-15
CXXFLAGS := -std=c++17 -O2 -Wall

SRC  := main.cpp
INP  := main.inp
OUTF := main.out
BIN  := main

OPEN ?= 1

# $(call find_recent,<dir>) -> directory of the most recently modified main.cpp under <dir>
# Uses `ls -t` (not `stat`) to sort by mtime, since stat's flags differ between
# BSD (macOS) and GNU (Linux) - this way it works on either host.
define find_recent
$(shell find "$(1)" -name $(SRC) 2>/dev/null | xargs ls -t 2>/dev/null | head -1 | xargs dirname)
endef

ifdef IS_LEAF
ABS := $(CURDIR)
else ifneq ($(strip $(P)),)
ABS := $(ROOT)/$(if $(SECTION),$(SECTION)/,)$(P)
else ifdef SECTION
ABS := $(call find_recent,$(ROOT)/$(SECTION))
else
ABS := $(call find_recent,$(ROOT))
endif

NEWDIR := $(ROOT)/$(if $(SECTION),$(SECTION)/,)$(P)

.PHONY: build run test edit clean where list help new

build: ## Compile main.cpp -> main
	@test -n "$(ABS)" || { echo "No problem resolved. Pass P=<path>, or cd into a problem dir."; exit 1; }
	@test -f "$(ABS)/$(SRC)" || { echo "No $(SRC) in $(ABS)"; exit 1; }
	cd "$(ABS)" && $(CXX) $(CXXFLAGS) -o $(BIN) $(SRC)

run: build ## Compile, then run with stdin/stdout attached to your terminal
	cd "$(ABS)" && ./$(BIN)

test: build ## Compile, run main.inp -> main.out, then print main.out
	cd "$(ABS)" && ./$(BIN) < $(INP) > $(OUTF)
	@echo "--- $(ABS)/$(OUTF) ---"
# 	@cat "$(ABS)/$(OUTF)"

edit: ## Open main.cpp/main.inp/main.out in VS Code
	@test -n "$(ABS)" || { echo "No problem resolved. Pass P=<path>, or cd into a problem dir."; exit 1; }
	code "$(ABS)/$(SRC)" "$(ABS)/$(INP)" "$(ABS)/$(OUTF)"

clean: ## Remove the compiled binary and stale output for this problem
	@test -z "$(ABS)" || rm -f "$(ABS)/$(BIN)" "$(ABS)/$(OUTF)"

where: ## Print the resolved problem directory (used by shell cd-helpers)
	@echo "$(ABS)"

list: ## List problem dirs here, newest first
	@find "$(if $(SECTION),$(ROOT)/$(SECTION),$(ROOT))" -name $(SRC) 2>/dev/null \
	  | xargs ls -t 2>/dev/null | xargs -I{} dirname {} | sed "s|$(ROOT)/||"

new: ## Scaffold (or safely revisit) a problem: make new P=2241/A
	@test -n "$(strip $(P))" || { echo "Usage: make new P=<path>  e.g. make new P=2241/A"; exit 1; }
	@mkdir -p "$(NEWDIR)"
	@[ -f "$(NEWDIR)/$(SRC)" ] || cp "$(ROOT)/template.cpp" "$(NEWDIR)/$(SRC)"
	@touch "$(NEWDIR)/$(INP)" "$(NEWDIR)/$(OUTF)"
	@printf 'IS_LEAF := 1\ninclude $$(shell git rev-parse --show-toplevel)/mk/common.mk\n' > "$(NEWDIR)/Makefile"
	@echo "Ready: $(NEWDIR)"
	@if [ "$(OPEN)" != "0" ]; then code "$(NEWDIR)/$(SRC)" "$(NEWDIR)/$(INP)" "$(NEWDIR)/$(OUTF)"; fi

help: ## Show this help
	@awk 'BEGIN{FS=":.*##"} /^[a-zA-Z_%-]+:.*##/{printf "  \033[36m%-8s\033[0m %s\n", $$1, $$2}' $(MAKEFILE_LIST)

include $(ROOT)/mk/docker.mk

.DEFAULT_GOAL := test
